<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Version>1.2.1</Version>
    <Authors>Niladri</Authors>
    <Company>MauiEssentials</Company>
    <Copyright>Copyright © 2026 Niladri</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/nuvyntralabs/MauiDev</RepositoryUrl>
    <PackageProjectUrl>https://nuvyntralabs.github.io/toolkits/maui-dev/</PackageProjectUrl>
  </PropertyGroup>
</Project>
