<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0-android;net10.0-ios</TargetFrameworks>
    <UseMaui>true</UseMaui>
    <SupportedOSPlatformVersion>24</SupportedOSPlatformVersion>
    <ApplicationId>com.nuvyntra.known.good</ApplicationId>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <MauiImage Include="Resources/Images/logo.png" />
  </ItemGroup>
</Project>
